### PR TITLE
Should fix tab complete for some commands.

### PR DESCRIPTION
**Pull request by PocketMiner82**
See code.

### CODE REVIEW

**Comment by Mundschutziii** [comment]
I don't use target because it's useless. If a player is banned, he can't be online and therefore you can't tab him.

**Comment by PocketMiner82** [comment]
Correct, but in Checkban, it should be possible to tabcomplete (if a user isn't banned, then he can be online)

**Comment by Mundschutziii** [comment]
But if a player is online and you want to see if he is banned, he cannot be banned because he is online.

**Comment by PocketMiner82** [comment]
Ok. I think, I'll close this.... xD

**Pull request closed without merging**
